<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/admin.php';
$user = admin_require_roles(['super_admin', 'admin', 'receptionist']);
if ($_SERVER['REQUEST_METHOD'] !== 'POST' || !csrf_valid()) { http_response_code(419); exit('Invalid request token.'); }
$db = db(); $uid = (int)$user['id']; $role = $user['role_name'];
$action = request_string($_POST, 'action'); $id = (int)($_POST['id'] ?? 0);
try {
    if ($action === 'reservation_status') {
        $status = request_string($_POST, 'status');
        if (!in_array($status, ['pending','confirmed','attended','no_show','cancelled'], true)) throw new RuntimeException('Invalid status.');
        $sql = 'SELECT r.* FROM reservations r WHERE r.id=? AND r.deleted_at IS NULL'.($role==='receptionist'?' AND r.branch_id IN (SELECT branch_id FROM branch_staff WHERE user_id='.$uid.' AND is_active=1)':'').' FOR UPDATE';
        $db->begin_transaction(); $q=$db->prepare($sql); $q->bind_param('i',$id); $q->execute(); $old=$q->get_result()->fetch_assoc();
        if (!$old) throw new RuntimeException('Reservation not found in your branch.');
        $q=$db->prepare('UPDATE reservations SET status=?, attended_at=IF(?="attended",COALESCE(attended_at,NOW()),NULL), cancelled_at=IF(?="cancelled",NOW(),NULL), cancelled_by=IF(?="cancelled",?,NULL), updated_by=? WHERE id=?');
        $q->bind_param('ssssiii',$status,$status,$status,$status,$uid,$uid,$id); $q->execute();
        $q=$db->prepare('INSERT INTO reservation_history (reservation_id,action,old_status,new_status,changed_by) VALUES (?,"status_changed",?,?,?)'); $q->bind_param('issi',$id,$old['status'],$status,$uid); $q->execute();
        admin_audit($db,$uid,'status_changed','reservations',$id,['status'=>$old['status']],['status'=>$status]); $db->commit(); admin_flash('success','Reservation status updated.'); admin_redirect('reservations');
    }
    if ($action === 'submission_status') {
        $status=request_string($_POST,'status'); $note=trim(request_string($_POST,'notes')); $reason=trim(request_string($_POST,'cancelled_reason'));
        if (!in_array($status,['new','contacted','completed','cancelled'],true) || mb_strlen($note)>5000 || mb_strlen($reason)>500) throw new RuntimeException('Invalid submission details.');
        $q=$db->prepare('SELECT status FROM form_submissions WHERE id=? AND deleted_at IS NULL'.($role==='receptionist'?' AND branch_id IN (SELECT branch_id FROM branch_staff WHERE user_id=? AND is_active=1)':'').' LIMIT 1');
        if($role==='receptionist')$q->bind_param('ii',$id,$uid);else $q->bind_param('i',$id);$q->execute();$old=$q->get_result()->fetch_assoc();if(!$old)throw new RuntimeException('Submission not found in your branch.');
        $q=$db->prepare('UPDATE form_submissions SET status=?, notes=?, cancelled_reason=?, contacted_at=IF(?="contacted",COALESCE(contacted_at,NOW()),contacted_at), contacted_by=IF(?="contacted",?,contacted_by), updated_by=? WHERE id=?');
        $q->bind_param('sssssiii',$status,$note,$reason,$status,$status,$uid,$uid,$id);$q->execute();admin_audit($db,$uid,'updated','form_submissions',$id,['status'=>$old['status']],['status'=>$status]);admin_flash('success','Submission updated.');admin_redirect('submissions');
    }
    if ($role === 'receptionist') throw new RuntimeException('Receptionists cannot manage site content or accounts.');
    if ($action === 'save_user') {
        if ($role !== 'super_admin' && ($role !== 'admin' || $id < 1)) throw new RuntimeException('Admins may edit existing accounts but cannot create them.');
        $name=trim(request_string($_POST,'name'));$email=trim(request_string($_POST,'email'));$phone=trim(request_string($_POST,'phone_number'));$pass=request_string($_POST,'password');$roleName=request_string($_POST,'role_name');$branchIds=array_values(array_unique(array_filter(array_map('intval',$_POST['branch_ids']??[]))));
        $isActive=isset($_POST['is_active'])?1:0;
        if($name===''||mb_strlen($name)>150||($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))||($phone===''&&$email==='')||($role==='super_admin'&&!in_array($roleName,['super_admin','admin','receptionist'],true))||($id===0&&strlen($pass)<12)||($pass!==''&&(strlen($pass)<12||strlen($pass)>1024)))throw new RuntimeException('Enter valid account details. Passwords must be 12 to 1024 characters.');
        if($role==='admin'){$q=$db->prepare('SELECT role_id FROM users WHERE id=? AND deleted_at IS NULL');$q->bind_param('i',$id);$q->execute();$target=$q->get_result()->fetch_assoc();if(!$target)throw new RuntimeException('Account not found.');$roleId=(int)$target['role_id'];$roleName=(string)$db->query('SELECT name FROM roles WHERE id='.$roleId)->fetch_assoc()['name'];if($roleName==='super_admin')throw new RuntimeException('Only a super admin can manage super admin accounts.');if($id===$uid&&!$isActive)throw new RuntimeException('You cannot deactivate your own account.');
            if($pass!==''){$hash=password_hash($pass,PASSWORD_DEFAULT);$q=$db->prepare('UPDATE users SET name=?,email=NULLIF(?,""),phone_number=NULLIF(?,""),password=?,is_active=?,updated_by=? WHERE id=?');$q->bind_param('ssssiii',$name,$email,$phone,$hash,$isActive,$uid,$id);}else{$q=$db->prepare('UPDATE users SET name=?,email=NULLIF(?,""),phone_number=NULLIF(?,""),is_active=?,updated_by=? WHERE id=?');$q->bind_param('sssiii',$name,$email,$phone,$isActive,$uid,$id);}$q->execute();admin_audit($db,$uid,'updated','users',$id,null,['name'=>$name,'is_active'=>$isActive]);admin_flash('success','Account updated.');admin_redirect('users');}
        $q=$db->prepare('SELECT id FROM roles WHERE name=?');$q->bind_param('s',$roleName);$q->execute();$roleId=(int)($q->get_result()->fetch_assoc()['id']??0);if(!$roleId)throw new RuntimeException('Role is missing from the SQL seed data.');
        if($id>0){$q=$db->prepare('SELECT role_id,is_active FROM users WHERE id=? AND deleted_at IS NULL');$q->bind_param('i',$id);$q->execute();$old=$q->get_result()->fetch_assoc();if(!$old)throw new RuntimeException('Account not found.');if($id===$uid&&!$isActive)throw new RuntimeException('You cannot deactivate your own account.');
            if($id===$uid && $roleName!=='super_admin')throw new RuntimeException('You cannot remove your own super admin role.');
            $superAdminRoleId=(int)($db->query("SELECT id FROM roles WHERE name='super_admin'")->fetch_assoc()['id']??0);
            if((int)$old['role_id']===$superAdminRoleId && (int)$old['is_active']===1 && (!$isActive || (int)$old['role_id']!==$roleId) && (int)$db->query("SELECT COUNT(*) n FROM users WHERE role_id=".(int)$old['role_id']." AND is_active=1 AND deleted_at IS NULL")->fetch_assoc()['n']<2)throw new RuntimeException('Keep at least one active super admin.');
            if($pass!==''){$hash=password_hash($pass,PASSWORD_DEFAULT);$q=$db->prepare('UPDATE users SET name=?,email=NULLIF(?,""),phone_number=NULLIF(?,""),password=?,role_id=?,is_active=?,updated_by=? WHERE id=?');$q->bind_param('ssssiiii',$name,$email,$phone,$hash,$roleId,$isActive,$uid,$id);}else{$q=$db->prepare('UPDATE users SET name=?,email=NULLIF(?,""),phone_number=NULLIF(?,""),role_id=?,is_active=?,updated_by=? WHERE id=?');$q->bind_param('sssiiii',$name,$email,$phone,$roleId,$isActive,$uid,$id);}$q->execute();
        }else{$hash=password_hash($pass,PASSWORD_DEFAULT);$q=$db->prepare('INSERT INTO users (role_id,name,email,phone_number,password,is_active,created_by) VALUES (?,?,NULLIF(?,""),NULLIF(?,""),?,?,?)');$q->bind_param('issssii',$roleId,$name,$email,$phone,$hash,$isActive,$uid);$q->execute();$id=(int)$db->insert_id;}
        $q=$db->prepare('UPDATE branch_staff SET is_active=0 WHERE user_id=?');$q->bind_param('i',$id);$q->execute();
        if($roleName==='receptionist')foreach($branchIds as $index=>$branchId){$q=$db->prepare('INSERT INTO branch_staff (branch_id,user_id,is_primary,is_active,created_by) VALUES (?,?,?,1,?) ON DUPLICATE KEY UPDATE is_primary=VALUES(is_primary),is_active=1');$primary=$index===0?1:0;$q->bind_param('iiii',$branchId,$id,$primary,$uid);$q->execute();}
        admin_audit($db,$uid,$id?'saved':'created','users',$id,null,['name'=>$name,'role'=>$roleName]);admin_flash('success','Account saved.');admin_redirect('users');
    }
    $simple=['save_banner'=>'banners','save_staff'=>'staff','save_branch'=>'branches','save_campaign'=>'campaigns'];
    if(isset($simple[$action])){
        $table=$simple[$action];$name=trim(request_string($_POST,'name'));$active=isset($_POST['is_active'])?1:0;$sort=(int)($_POST['sort_order']??0);
        if($table==='banners'){$title=trim(request_string($_POST,'title'));$subtitle=trim(request_string($_POST,'subtitle'));$image=trim(request_string($_POST,'image_path'));$button=trim(request_string($_POST,'button_text'));$link=trim(request_string($_POST,'button_link'));if($image==='')throw new RuntimeException('Banner image path is required.');
          if($id){$q=$db->prepare('UPDATE banners SET title=?,subtitle=?,image_path=?,button_text=?,button_link=?,is_active=?,sort_order=?,updated_by=? WHERE id=?');$q->bind_param('sssssiiii',$title,$subtitle,$image,$button,$link,$active,$sort,$uid,$id);}else{$q=$db->prepare('INSERT INTO banners(title,subtitle,image_path,button_text,button_link,is_active,sort_order,created_by) VALUES(?,?,?,?,?,?,?,?)');$q->bind_param('sssssiii',$title,$subtitle,$image,$button,$link,$active,$sort,$uid);}}
        elseif($table==='staff'){$title=trim(request_string($_POST,'title'));$specialty=trim(request_string($_POST,'specialty'));$image=trim(request_string($_POST,'image_path'));$bio=trim(request_string($_POST,'bio'));if($name==='')throw new RuntimeException('Staff name is required.');if($id){$q=$db->prepare('UPDATE staff SET name=?,title=?,specialty=?,image_path=?,bio=?,is_active=?,sort_order=?,updated_by=? WHERE id=?');$q->bind_param('sssssiiii',$name,$title,$specialty,$image,$bio,$active,$sort,$uid,$id);}else{$q=$db->prepare('INSERT INTO staff(name,title,specialty,image_path,bio,is_active,sort_order,created_by) VALUES(?,?,?,?,?,?,?,?)');$q->bind_param('sssssiii',$name,$title,$specialty,$image,$bio,$active,$sort,$uid);}}
        elseif($table==='branches'){$code=trim(request_string($_POST,'code'));$address=trim(request_string($_POST,'address'));$phone=trim(request_string($_POST,'phone_number'));$email=trim(request_string($_POST,'email'));$map=trim(request_string($_POST,'google_map_link'));if($name===''||$code===''||$address==='')throw new RuntimeException('Branch name, code and address are required.');if($id){$q=$db->prepare('UPDATE branches SET code=?,name=?,address=?,phone_number=NULLIF(?,""),email=NULLIF(?,""),google_map_link=NULLIF(?,""),is_active=?,sort_order=?,updated_by=? WHERE id=?');$q->bind_param('ssssssiiii',$code,$name,$address,$phone,$email,$map,$active,$sort,$uid,$id);}else{$q=$db->prepare('INSERT INTO branches(code,name,address,phone_number,email,google_map_link,is_active,sort_order,created_by) VALUES(?,?,?,NULLIF(?,""),NULLIF(?,""),NULLIF(?,""),?,?,?)');$q->bind_param('ssssssiii',$code,$name,$address,$phone,$email,$map,$active,$sort,$uid);}}
        else{$code=trim(request_string($_POST,'code'));$slug=trim(request_string($_POST,'slug'));$description=trim(request_string($_POST,'description'));$image=trim(request_string($_POST,'image_path'));$max=trim(request_string($_POST,'max_reservations'));$maxValue=$max===''?null:(int)$max;if($name===''||$code==='')throw new RuntimeException('Campaign name and code are required.');if($id){$q=$db->prepare('UPDATE campaigns SET name=?,code=?,slug=NULLIF(?,""),description=?,image_path=?,max_reservations=?,is_active=?,sort_order=?,updated_by=? WHERE id=?');$q->bind_param('sssssiiiii',$name,$code,$slug,$description,$image,$maxValue,$active,$sort,$uid,$id);}else{$q=$db->prepare('INSERT INTO campaigns(name,code,slug,description,image_path,max_reservations,is_active,sort_order,created_by) VALUES(?,?,NULLIF(?,""),?,?,?, ?,?,?)');$q->bind_param('sssssiiii',$name,$code,$slug,$description,$image,$maxValue,$active,$sort,$uid);}}
        $q->execute();if(!$id)$id=(int)$db->insert_id;admin_audit($db,$uid,'saved',$table,$id);admin_flash('success','Changes saved.');admin_redirect($table);
    }
    if($action==='save_settings'){
        $settings=[];foreach(['lab_name','about','logo_path','favicon_path','phone_number','whatsapp_number','email','address','google_map_link','working_hours','facebook_url','instagram_url','youtube_url','tiktok_url'] as $key)$settings[$key]=trim(request_string($_POST,$key));
        $columns=implode(',',array_keys($settings));$marks=implode(',',array_fill(0,count($settings),'?'));$types=str_repeat('s',count($settings));$vals=array_values($settings);$q=$db->prepare('SELECT id FROM lab_settings ORDER BY id LIMIT 1');$q->execute();$row=$q->get_result()->fetch_assoc();if($row){$pairs=implode(',',array_map(fn($k)=>"$k=?",array_keys($settings)));$vals[]=$uid;$vals[]=(int)$row['id'];$types.='ii';$q=$db->prepare("UPDATE lab_settings SET $pairs,updated_by=?,id=?");$q->bind_param($types,...$vals);}else{$vals[]=$uid;$types.='i';$q=$db->prepare("INSERT INTO lab_settings ($columns,created_by) VALUES ($marks,?)");$q->bind_param($types,...$vals);}$q->execute();
        $colors=[];foreach(['primary','secondary','accent','background','surface','text'] as $token)foreach(['light','dark'] as $mode){$key=$token.'_'.$mode;$colors[$key]=safe_hex(request_string($_POST,$key),'#000000');}
        $has=(bool)$db->query('SELECT id FROM theme_settings LIMIT 1')->fetch_assoc();if($has){$set=implode(',',array_map(fn($k)=>"$k=?",array_keys($colors)));$q=$db->prepare("UPDATE theme_settings SET $set WHERE id=(SELECT id FROM (SELECT id FROM theme_settings LIMIT 1) t)");$q->bind_param(str_repeat('s',count($colors)),...array_values($colors));}else{$cols=implode(',',array_keys($colors));$marks=implode(',',array_fill(0,count($colors),'?'));$q=$db->prepare("INSERT INTO theme_settings ($cols) VALUES ($marks)");$q->bind_param(str_repeat('s',count($colors)),...array_values($colors));}$q->execute();admin_audit($db,$uid,'updated','lab_settings',1);admin_flash('success','Site settings and theme saved.');admin_redirect('settings');
    }
    throw new RuntimeException('Unknown action.');
}catch(Throwable $e){if($db->errno)try{$db->rollback();}catch(Throwable){}admin_flash('danger',$e instanceof mysqli_sql_exception?'Unable to save. Check unique values and required SQL tables.':$e->getMessage());admin_redirect(match($action){'save_user'=>'users','save_banner'=>'banners','save_staff'=>'staff','save_branch'=>'branches','save_campaign'=>'campaigns','save_settings'=>'settings','reservation_status'=>'reservations','submission_status'=>'submissions',default=>'dashboard'});}
